changelog:
  categories:
    - title: 🛠 Breaking Changes
      labels:
        - major-update
        - breaking-change
    - title: 🛠 Dependency Upgrades
      labels:
        - dependencies
      exclude:
        labels:
          - major-update
    - title: ⭐ New Features
      labels:
        - "*"